---
title: Alliance of Eastside Agencies Directory
tagline: Connecting Eastside residents with essential human services across housing, health, food, education, and more.
email: rochelle.claytonstrunk@encompassnw.org
description: >- # this means to ignore newlines until "baseurl:"
  The Alliance of Eastside Agencies Directory connects community members to local human-services providers, covering housing, food, health, education, and more. It promotes access, awareness, and collaboration across East King County, helping families, youth, seniors, and individuals find essential services while strengthening the region’s nonprofit and government service network.
baseurl: ""
url: "https://aea.directory"

collections:
  agencies:
    output: true
  events:
    output: true
defaults:
  - scope:
      path: "_agencies"
      type: "agencies"
    values:
      layout: "agency"
  - scope:
      path: "_events"
      type: "events"
    values:
      layout: "event"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - mise.toml
  - README.md
  - script
  - vendor
future: true
plugins:
  - jekyll-seo-tag
